on:
  push:
    branches:
      - docs/add-auto-label-merge-action
jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: mschilde/auto-label-merge-conflicts@master
        with:
          CONFLICT_LABEL_NAME: "S: has merge conflicts"
          GITHUB_TOKEN: ${{ secrets.MERGE_CONFLICT_WORKFLOW }}
